----
- hosts: linux
  vars: 
    training:
      tropic: ansible
      lab: azure
      mode: online
  tasks:
  - name: print dic vars
    debug: 
     msg: "key is {{ item.key }} and value is {{ item.value }}"
    with_dict: "{{ training }}"
