---
- hosts: linux
  strategy: free
  tasks: 
  - name: task 1
    shell: 
      cmd: "sleep 10 && uptime"
    register: result1
  - name: task 1 output
    debug: 
      msg: "Tasks 1 ou put is {{ result1.stdout }} "
  - name: task 2
    shell: 
      cmd: "sleep 5 && w "
    register: result2
  - name: task2 result
    debug: 
      msg: "Task 2 outpt is {{ result2.stdout }}"

