---
- hosts: ubuntu
  become: yes
  tasks:
  - name: install mariadb server
    apt:  
      name: mariadb-server
      state: latest
    tags:
    - install
    - setup
    - all 
  - name: start 
    service: 
      name: mariadb
      state: started
    tags:
    - start
    - setup
    - all
  - name: restart mariadb server
    service:
      name: mariadb
      state: restarted
    tags:
    - restart
  - name: stop mariadb server
    service:
      name: mariadb
      state: stopped
    tags:
    - stop
  - name: create mariadb user
    user:
       name: mariadbuser
       state: present
    tags:
    - user
    - all
      


